language:
- java
jdk:
- openjdk7
before_script:
- if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
- sudo wget -q http://dl.google.com/android/android-sdk_r22-linux.tgz 
- sudo tar xzvf android-sdk_r22-linux.tgz > /dev/null
- export ANDROID_HOME=`pwd`/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo y | sudo android-sdk-linux/tools/android update sdk -a -t tools,platform-tools,build-tools-19.0.1,android-19 --no-ui
- wget http://services.gradle.org/distributions/gradle-1.9-bin.zip
- unzip -qq gradle-1.9-bin.zip
- export GRADLE_HOME=$PWD/gradle-1.9
- export PATH=$GRADLE_HOME/bin:$PATH
- java -version
- gradle -v

script:
- gradle assemble 

